package com.poslyt.rupeering

import android.content.ContentValues
import android.content.Context
import android.database.sqlite.SQLiteDatabase
import android.database.sqlite.SQLiteOpenHelper
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

class DatabaseManager(context: Context) : SQLiteOpenHelper(context, DATABASE_NAME, null, DATABASE_VERSION) {

    companion object {
        private const val DATABASE_VERSION = 1
        private const val DATABASE_NAME = "auto_alert.db"
        private const val TABLE_TRANSACTIONS = "transactions"
        private const val KEY_ID = "id"
        private const val KEY_APP_NAME = "app_name"
        private const val KEY_AMOUNT = "amount"
        private const val KEY_TIMESTAMP = "timestamp"
    }

    override fun onCreate(db: SQLiteDatabase) {
        // We do not manage schema creation via Kotlin because 
        // sqflite (Dart side) might handle onCreate. 
        // We only append to the existing DB created by the app.
        val createTableQuery = ("CREATE TABLE IF NOT EXISTS " + TABLE_TRANSACTIONS + "("
                + KEY_ID + " INTEGER PRIMARY KEY AUTOINCREMENT," 
                + KEY_APP_NAME + " TEXT,"
                + KEY_AMOUNT + " TEXT," 
                + KEY_TIMESTAMP + " TEXT" + ")")
        db.execSQL(createTableQuery)
    }

    override fun onUpgrade(db: SQLiteDatabase, oldVersion: Int, newVersion: Int) {
        // Should be handled by dart sqflite ideally.
    }

    fun insertTransaction(appName: String, amount: String) {
        val db = this.writableDatabase
        
        // Match the ISO8601 string generated by DateTime.now().toIso8601String()
        val sdf = SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS", Locale.US)
        val timestamp = sdf.format(Date())

        val values = ContentValues()
        values.put(KEY_APP_NAME, appName)
        values.put(KEY_AMOUNT, amount)
        values.put(KEY_TIMESTAMP, timestamp)

        db.insert(TABLE_TRANSACTIONS, null, values)
        db.close()
    }
}
